---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/exchanges":
    get:
      summary: Get all paginated exchanges
      tags:
      - Exchanges
      parameters:
      - name: page
        in: query
        description: Current page number
        example: 1
        schema:
          type: integer
      - name: items
        in: query
        description: Number of items per page(default 20 and maximum of 100)
        example: 20
        schema:
          type: integer
      - name: name
        in: query
        description: Name of the exchange you want to find
        example: Nasdaq Stock Market
        schema:
          type: string
      - name: mic
        in: query
        description: Mic of the exchange you want to find
        example: XNAS
        schema:
          type: string
      responses:
        '200':
          description: Exchanges retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        mic:
                          type: string
                          example: XNAS
                        name:
                          type: string
                          example: Nasdaq Stock Market
                      required:
                      - id
                      - mic
                      - name
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      pages_count:
                        type: integer
                        example: 13
                      render_count:
                        type: integer
                        example: 1
                      items_count:
                        type: integer
                        example: 13
                      prev_url:
                        type: string
                        example: "/api/v1/exchanges?page="
                      next_url:
                        type: string
                        example: "/api/v1/exchanges?page=2"
                    required:
                    - current_page
                    - pages_count
                    - render_count
                    - items_count
                required:
                - records
        '400':
          description: Invalid page input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: expected :page in 1..2; got 3
    post:
      summary: Create an exchange
      tags:
      - Exchanges
      parameters: []
      responses:
        '201':
          description: Created exchange
          content:
            application/json:
              schema:
                type: object
                properties:
                  mic:
                    type: string
                    example: XNAS
                  name:
                    type: string
                    example: Nasdaq Stock Market
                required:
                - mic
                - name
        '422':
          description: Invalid params
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      mic:
                        type: array
                        items:
                          type: string
                        example:
                        - mic can only contain letters and numbers
                      name:
                        type: array
                        items:
                          type: string
                        example:
                        - can't be blank
                        - is too long (maximum is 256 characters)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mic:
                  type: string
                  example: XNAS
                name:
                  type: string
                  example: Nasdaq Stock Market
              required:
              - mic
              - name
  "/api/v1/exchanges/{id}":
    get:
      summary: Retrieves just one exchange
      tags:
      - Exchanges
      parameters:
      - name: id
        in: path
        description: ID of the exchange to retrieve
        example: '1'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Exchange found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  mic:
                    type: string
                    example: XNAS
                  name:
                    type: string
                    example: Nasdaq Stock Market
                required:
                - id
                - mic
                - name
        '404':
          description: Exchange not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Exchange not found
    put:
      summary: Updates entire exchange
      tags:
      - Exchanges
      parameters:
      - name: id
        in: path
        description: ID of the exchange to update
        example: '1'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Exchange updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  mic:
                    type: string
                    example: XNAS
                  name:
                    type: string
                    example: Nasdaq Stock Market
                required:
                - id
                - mic
                - name
        '404':
          description: Exchange not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Exchange not found
        '422':
          description: Invalid params
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      mic:
                        type: array
                        items:
                          type: string
                        example:
                        - mic can only contain letters and numbers
                      name:
                        type: array
                        items:
                          type: string
                        example:
                        - can't be blank
                        - is too long (maximum is 256 characters)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mic:
                  type: string
                  example: XNAS
                name:
                  type: string
                  example: Nasdaq Stock Market
    patch:
      summary: Updates the part of exchange
      tags:
      - Exchanges
      parameters:
      - name: id
        in: path
        description: ID of the exchange to update
        example: '1'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Exchange updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  mic:
                    type: string
                    example: XNAS
                  name:
                    type: string
                    example: Nasdaq Stock Market
                required:
                - id
                - mic
                - name
        '404':
          description: Exchange not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Exchange not found
        '422':
          description: Invalid params
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      mic:
                        type: array
                        items:
                          type: string
                        example:
                        - mic can only contain letters and numbers
                      name:
                        type: array
                        items:
                          type: string
                        example:
                        - can't be blank
                        - is too long (maximum is 256 characters)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mic:
                  type: string
                  example: XNAS
                name:
                  type: string
                  example: Nasdaq Stock Market
              required:
              - mic
              - name
    delete:
      summary: Deletes an exchange
      tags:
      - Exchanges
      parameters:
      - name: id
        in: path
        description: ID of the exchange to update
        example: '1'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Exchange deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  mic:
                    type: string
                    example: XNAS
                  name:
                    type: string
                    example: Nasdaq Stock Market
                required:
                - id
                - mic
                - name
        '404':
          description: Exchange not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Exchange not found
servers:
- url: http://localhost:3000
  description: Development Server
